# Introduction to Data Science
## Homework 2

Student Name: Ruofan Wang

Student Netid: rw2268 
***

### Part 1: Case study
- Read [this article](http://www.nytimes.com/2012/02/19/magazine/shopping-habits.html) in the New York Times.
- Use what we've learned in class and from the book to describe how one could set Target's problem up as a predictive modeling problem, such that they could have gotten the results that they did.  Formulate your solution as a proposed plan using our data science terminology.  Include all the aspects of the formulation that you see as relevant to solving the problem.  Be precise but concise.

Place your answer here!

Target wants to predict whether a certain customer has been pregnant or not, based on their purchase history and their own data. This can be regarded as a predictive analysis problem because we use our historical data (user personal information and purchase history) to predict the future trend (pregnant or not).

To solve this predictive analysis problem, we need to define our target variable. In this case, it is a binary variable: whether the customer has been pregnant. Once we have our goal, we need to collect useful information and sufficient data. One credit card number or other bank account can be regarded as a sample, which represents a unique customer. Their purchase history and some personal information can be collected as variables in the model. Since the outcome is binary (0 or 1), we can use logistic regression to predict it. 

Of course we need to do some data cleaning to remove noise and then do some data pre-processing, like standardize or whitening. Then, we should select useful features. We can use the mutual information or the variable importance in the decision tree to achieve that, which can be easily obtained in sklearn.

After preparing data, we can fit the logistic regression model into it. We should use MLE to estimate parameters.

The result of the regression is the probability for a certain customer to be pregnant. If the probability is larger than 0.5, we can figure this customer has been pregnant.

### Part 2: Exploring data in the command line
For this part we will be using the data file located in `"advertising_events.csv"`. This file consists of records that pertain to some online advertising events on a given day. There are 4 comma separated columns in this order: `userid`, `timestamp`, `domain`, and `action`. These fields are of type `int`, `int`, `string`, and `int` respectively. Answer the following questions using Linux/Unix bash commands. All questions can be answered in one line (sometimes, with pipes)! Some questions will have many possible solutions. Don't forget that in IPython notebooks you must prefix all bash commands with an exclamation point, i.e. `"!command arguments"`.

[Hints: You can experiment with whatever you want in the notebook and then delete things to construct your answer later.  You can also use ssh to use the actual bash shell in your terminal and then just paste your answers here. Recall that once you enter the "!" then filename completion should work. Also, these are standard data exploration commands that are quick and easy to use in a terminal or in the notebook. We don't cover command line operations formally in this class, but these are worth learning (and thus are part of the HW). Be resourceful. Use whatever online cheat sheets or Stackoverflow to answer the question.]

1\. How many records (lines) are in this file (look up wc)?

In [1]:
%env filename=./advertising_events.csv

env: filename=./advertising_events.csv

In [2]:
# Place your code here
!wc -l $filename

   10341 ./advertising_events.csv

2\. How many unique users are in this file? (hint: consider the 'cut' command and use pipe operator '|')

In [20]:
# Place your code here
!awk -F"[,]" '{print $1}' $filename > userid.txt 
!sort ./userid.txt > userid_sort.txt 
!uniq ./userid_sort.txt > userid_sort_uniq.txt
!wc -l userid_sort_uniq.txt

     732 userid_sort_uniq.txt

3\. Rank all domains by the number of visits they received in descending order. (hint: consider the 'cut', 'uniq' and 'sort' commands and the pipe operator).

In [26]:
# Place your code here
!awk -F"[,]" '{print $3}' $filename > domain.txt
!sort domain.txt > domain_s.txt 
!uniq -c domain_s.txt | sort -r

3114 google.com
2092 facebook.com
1036 youtube.com
1034 yahoo.com
1022 baidu.com
 513 wikipedia.org
 511 amazon.com
 382 qq.com
 321 twitter.com
 316 taobao.com

4\. List all records for the user with user id 37. (hint: this can be done using 'grep')

In [29]:
# Place your code here
!awk -F[","] '{if ($1==37) { print $0; }}' $filename

37,648061658,google.com,0
37,642479972,google.com,2
37,644493341,facebook.com,2
37,654941318,facebook.com,1
37,649979874,baidu.com,1
37,653061949,yahoo.com,1
37,655020469,google.com,3
37,640878012,amazon.com,0
37,659864136,youtube.com,1
37,640361378,yahoo.com,1
37,653862134,facebook.com,0
37,648828970,youtube.com,0

### Part 3: Dealing with data Pythonically

In [1]:
# You might find these packages useful. You may import any others you want!
import pandas as pd
import numpy as np

1\. Load the data set `"ads_dataset.tsv"` into a Python Pandas data frame called `ads`.

In [2]:
# Place your code here
ads = pd.read_csv('ads_dataset.tsv', sep='\t')

2\. Write a Python function called `getDfSummary()` that does the following:
- Takes as input a data frame
- For each variable in the data frame calculates the following features:
  - `number_nan` to count the number of missing not-a-number values
  - Ignoring missing, NA, and Null values:
    - `number_distinct` to count the number of distinct values a variable can take on
    - `mean`, `max`, `min`, `std` (standard deviation), and `25%`, `50%`, `75%` to correspond to the appropriate percentiles
- All of these new features should be loaded in a new data frame. Each row of the data frame should be a variable from the input data frame, and the columns should be the new summary features.
- Returns this new data frame containing all of the summary information

Hint: The pandas `describe()` [(manual page)](http://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.describe.html) method returns a useful series of values that can be used here.

In [73]:
def getDfSummary(input_data):
    # Place your code here
    output_data = input_data.describe().transpose()
    output_data['number_nan'] = input_data.isnull().sum()
    output_data.rename(columns = {'count' : 'number_distinct'}, inplace = True)
    return output_data

In [5]:
d = ads.describe().transpose()

In [6]:
d

,count,mean,std,min,25%,50%,75%,max
isbuyer,54584.0,0.042632,0.202027,0.0000,0.0,0.0,0.000000,1.00000
buy_freq,2327.0,1.240653,0.782228,1.0000,1.0,1.0,1.000000,15.00000
visit_freq,54584.0,1.852777,2.921820,0.0000,1.0,1.0,2.000000,84.00000
buy_interval,54584.0,0.210008,3.922016,0.0000,0.0,0.0,0.000000,174.62500
sv_interval,54584.0,5.825610,17.595442,0.0000,0.0,0.0,0.104167,184.91670
expected_time_buy,54584.0,-0.198040,4.997792,-181.9238,0.0,0.0,0.000000,84.28571
expected_time_visit,54584.0,-10.210786,31.879722,-187.6156,0.0,0.0,0.000000,91.40192
last_buy,54584.0,64.729335,53.476658,0.0000,18.0,51.0,105.000000,188.00000
last_visit,54584.0,64.729335,53.476658,0.0000,18.0,51.0,105.000000,188.00000
multiple_buy,54584.0,0.006357,0.079479,0.0000,0.0,0.0,0.000000,1.00000
multiple_visit,54584.0,0.277444,0.447742,0.0000,0.0,0.0,1.000000,1.00000
uniq_urls,54584.0,86.569343,61.969765,-1.0000,30.0,75.0,155.000000,206.00000
num_checkins,54584.0,720.657592,1275.727306,1.0000,127.0,319.0,802.000000,37091.00000
y_buy,54584.0,0.004635,0.067924,0.0000,0.0,0.0,0.000000,1.00000

In [75]:
getDfSummary(ads)

,number_distinct,mean,std,min,25%,50%,75%,max,number_nan
isbuyer,54584.0,0.042632,0.202027,0.0000,0.0,0.0,0.000000,1.00000,0
buy_freq,2327.0,1.240653,0.782228,1.0000,1.0,1.0,1.000000,15.00000,52257
visit_freq,54584.0,1.852777,2.921820,0.0000,1.0,1.0,2.000000,84.00000,0
buy_interval,54584.0,0.210008,3.922016,0.0000,0.0,0.0,0.000000,174.62500,0
sv_interval,54584.0,5.825610,17.595442,0.0000,0.0,0.0,0.104167,184.91670,0
expected_time_buy,54584.0,-0.198040,4.997792,-181.9238,0.0,0.0,0.000000,84.28571,0
expected_time_visit,54584.0,-10.210786,31.879722,-187.6156,0.0,0.0,0.000000,91.40192,0
last_buy,54584.0,64.729335,53.476658,0.0000,18.0,51.0,105.000000,188.00000,0
last_visit,54584.0,64.729335,53.476658,0.0000,18.0,51.0,105.000000,188.00000,0
multiple_buy,54584.0,0.006357,0.079479,0.0000,0.0,0.0,0.000000,1.00000,0
multiple_visit,54584.0,0.277444,0.447742,0.0000,0.0,0.0,1.000000,1.00000,0
uniq_urls,54584.0,86.569343,61.969765,-1.0000,30.0,75.0,155.000000,206.00000,0
num_checkins,54584.0,720.657592,1275.727306,1.0000,127.0,319.0,802.000000,37091.00000,0
y_buy,54584.0,0.004635,0.067924,0.0000,0.0,0.0,0.000000,1.00000,0

3\. How long does it take for your `getDfSummary()` function to work on your `ads` data frame? Show us the results below.

Hint: `%timeit getDfSummary(ads)`

In [76]:
# Place your code here
%timeit getDfSummary(ads)

10 loops, best of 3: 58.6 ms per loop

4\. Using the results returned from `getDfSummary()`, which fields, if any, contain missing `NaN` values?

In [78]:
# Place your code here
result = getDfSummary(ads)
result['number_nan'] > 0

isbuyer                False
buy_freq                True
visit_freq             False
buy_interval           False
sv_interval            False
expected_time_buy      False
expected_time_visit    False
last_buy               False
last_visit             False
multiple_buy           False
multiple_visit         False
uniq_urls              False
num_checkins           False
y_buy                  False
Name: number_nan, dtype: bool

5\. For the fields with missing values, does it look like the data is missing at random? Are there any other fields that correlate perfectly, or predict that the data is missing? If missing, what should the data value be?

Hint: create another data frame that has just the records with a missing value. Get a summary of this data frame using `getDfSummary()` and compare the differences. Do some feature distributions change dramatically?

In [98]:
# Place your code here
ads2 = ads.copy()

In [99]:
filter2 = ads2.isnull().sum(axis = 1) > 0

In [100]:
ads2 = ads2[filter2]

In [101]:
ads2.head()

,isbuyer,buy_freq,visit_freq,buy_interval,sv_interval,expected_time_buy,expected_time_visit,last_buy,last_visit,multiple_buy,multiple_visit,uniq_urls,num_checkins,y_buy
NaN,0,NaN,1,0.0,0.0,0.0,0.0000,106,106,0,0,169,2130,0
NaN,0,NaN,1,0.0,0.0,0.0,0.0000,72,72,0,0,154,1100,0
NaN,0,NaN,1,0.0,0.0,0.0,0.0000,5,5,0,0,4,12,0
NaN,0,NaN,1,0.0,0.0,0.0,0.0000,6,6,0,0,150,539,0
NaN,0,NaN,2,0.0,0.5,0.0,-101.1493,101,101,0,1,103,362,0

In [103]:
getDfSummary(ads2)

,number_distinct,mean,std,min,25%,50%,75%,max,number_nan
isbuyer,52257.0,0.000000,0.000000,0.0000,0.0,0.0,0.000000,0.00000,0
buy_freq,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,52257
visit_freq,52257.0,1.651549,2.147955,1.0000,1.0,1.0,2.000000,84.00000,0
buy_interval,52257.0,0.000000,0.000000,0.0000,0.0,0.0,0.000000,0.00000,0
sv_interval,52257.0,5.686388,17.623555,0.0000,0.0,0.0,0.041667,184.91670,0
expected_time_buy,52257.0,0.000000,0.000000,0.0000,0.0,0.0,0.000000,0.00000,0
expected_time_visit,52257.0,-9.669298,31.239030,-187.6156,0.0,0.0,0.000000,91.40192,0
last_buy,52257.0,65.741317,53.484622,0.0000,19.0,52.0,106.000000,188.00000,0
last_visit,52257.0,65.741317,53.484622,0.0000,19.0,52.0,106.000000,188.00000,0
multiple_buy,52257.0,0.000000,0.000000,0.0000,0.0,0.0,0.000000,0.00000,0
multiple_visit,52257.0,0.255602,0.436203,0.0000,0.0,0.0,1.000000,1.00000,0
uniq_urls,52257.0,86.656180,61.996711,-1.0000,30.0,75.0,155.000000,206.00000,0
num_checkins,52257.0,721.848518,1284.504018,1.0000,126.0,318.0,803.000000,37091.00000,0
y_buy,52257.0,0.003024,0.054904,0.0000,0.0,0.0,0.000000,1.00000,0

In [109]:
pd.concat([getDfSummary(ads), getDfSummary(ads2)], axis = 1)

,number_distinct,mean,std,min,25%,50%,75%,max,number_nan,number_distinct,mean,std,min,25%,50%,75%,max,number_nan
isbuyer,54584.0,0.042632,0.202027,0.0000,0.0,0.0,0.000000,1.00000,0,52257.0,0.000000,0.000000,0.0000,0.0,0.0,0.000000,0.00000,0
buy_freq,2327.0,1.240653,0.782228,1.0000,1.0,1.0,1.000000,15.00000,52257,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,52257
visit_freq,54584.0,1.852777,2.921820,0.0000,1.0,1.0,2.000000,84.00000,0,52257.0,1.651549,2.147955,1.0000,1.0,1.0,2.000000,84.00000,0
buy_interval,54584.0,0.210008,3.922016,0.0000,0.0,0.0,0.000000,174.62500,0,52257.0,0.000000,0.000000,0.0000,0.0,0.0,0.000000,0.00000,0
sv_interval,54584.0,5.825610,17.595442,0.0000,0.0,0.0,0.104167,184.91670,0,52257.0,5.686388,17.623555,0.0000,0.0,0.0,0.041667,184.91670,0
expected_time_buy,54584.0,-0.198040,4.997792,-181.9238,0.0,0.0,0.000000,84.28571,0,52257.0,0.000000,0.000000,0.0000,0.0,0.0,0.000000,0.00000,0
expected_time_visit,54584.0,-10.210786,31.879722,-187.6156,0.0,0.0,0.000000,91.40192,0,52257.0,-9.669298,31.239030,-187.6156,0.0,0.0,0.000000,91.40192,0
last_buy,54584.0,64.729335,53.476658,0.0000,18.0,51.0,105.000000,188.00000,0,52257.0,65.741317,53.484622,0.0000,19.0,52.0,106.000000,188.00000,0
last_visit,54584.0,64.729335,53.476658,0.0000,18.0,51.0,105.000000,188.00000,0,52257.0,65.741317,53.484622,0.0000,19.0,52.0,106.000000,188.00000,0
multiple_buy,54584.0,0.006357,0.079479,0.0000,0.0,0.0,0.000000,1.00000,0,52257.0,0.000000,0.000000,0.0000,0.0,0.0,0.000000,0.00000,0
multiple_visit,54584.0,0.277444,0.447742,0.0000,0.0,0.0,1.000000,1.00000,0,52257.0,0.255602,0.436203,0.0000,0.0,0.0,1.000000,1.00000,0
uniq_urls,54584.0,86.569343,61.969765,-1.0000,30.0,75.0,155.000000,206.00000,0,52257.0,86.656180,61.996711,-1.0000,30.0,75.0,155.000000,206.00000,0
num_checkins,54584.0,720.657592,1275.727306,1.0000,127.0,319.0,802.000000,37091.00000,0,52257.0,721.848518,1284.504018,1.0000,126.0,318.0,803.000000,37091.00000,0
y_buy,54584.0,0.004635,0.067924,0.0000,0.0,0.0,0.000000,1.00000,0,52257.0,0.003024,0.054904,0.0000,0.0,0.0,0.000000,1.00000,0

It seems that the missing data is not randomly missed. The variable called 'buy_freq' is highly dependent on some other variables. 
They are: isbuyer, buy_interval, expected_time_buy, multiple_buy.
Because after pulling out the samples with missing values, these variables will change significantly.

6\. Which variables are binary?

In [110]:
# Place your code here
getDfSummary(ads)

,number_distinct,mean,std,min,25%,50%,75%,max,number_nan
isbuyer,54584.0,0.042632,0.202027,0.0000,0.0,0.0,0.000000,1.00000,0
buy_freq,2327.0,1.240653,0.782228,1.0000,1.0,1.0,1.000000,15.00000,52257
visit_freq,54584.0,1.852777,2.921820,0.0000,1.0,1.0,2.000000,84.00000,0
buy_interval,54584.0,0.210008,3.922016,0.0000,0.0,0.0,0.000000,174.62500,0
sv_interval,54584.0,5.825610,17.595442,0.0000,0.0,0.0,0.104167,184.91670,0
expected_time_buy,54584.0,-0.198040,4.997792,-181.9238,0.0,0.0,0.000000,84.28571,0
expected_time_visit,54584.0,-10.210786,31.879722,-187.6156,0.0,0.0,0.000000,91.40192,0
last_buy,54584.0,64.729335,53.476658,0.0000,18.0,51.0,105.000000,188.00000,0
last_visit,54584.0,64.729335,53.476658,0.0000,18.0,51.0,105.000000,188.00000,0
multiple_buy,54584.0,0.006357,0.079479,0.0000,0.0,0.0,0.000000,1.00000,0
multiple_visit,54584.0,0.277444,0.447742,0.0000,0.0,0.0,1.000000,1.00000,0
uniq_urls,54584.0,86.569343,61.969765,-1.0000,30.0,75.0,155.000000,206.00000,0
num_checkins,54584.0,720.657592,1275.727306,1.0000,127.0,319.0,802.000000,37091.00000,0
y_buy,54584.0,0.004635,0.067924,0.0000,0.0,0.0,0.000000,1.00000,0

isbuyer, multiple_buy, multiple_visit, y_buy

In [ ]:
feature = ['isbuyer, multiple_buy, multiple_visit, y_buy']